export * from "./IconAuth";
export * from "./IconMediaSendChat";
export * from "./IconWalletApp";

export { default as IconAdd } from "./IconAdd";
export { default as IconArrowRight } from "./IconArrowRight";
export { default as IconBantuan } from "./IconBantuan";
export { default as IconBisu } from "./IconBisu";
export { default as IconCall } from "./IconCall";
export { default as IconCerita } from "./IconCerita";
export { default as IconChannel } from "./IconChannel";
export { default as IconChat } from "./IconChat";
export { default as IconEdit } from "./IconEdit";
export { default as IconEnkripsi } from "./IconEnkripsi";
export { default as IconForward } from "./IconForward";
export { default as IconFoto } from "./IconFoto";
export { default as IconGame } from "./IconGame";
export { default as IconGear } from "./IconGear";
export { default as IconGroup } from "./IconGroup";
export { default as IconKirim } from "./IconKirim";
export { default as IconLogout } from "./IconLogout";
export { default as IconMusic } from "./IconMusic";
export { default as IconNearby } from "./IconNearby";
export { default as IconNewChat } from "./IconNewChat";
export { default as IconNotifikasi } from "./IconNotifikasi";
export { default as IconPrivacy } from "./IconPrivacy";
export { default as IconProfile } from "./IconProfile";
export { default as IconReply } from "./IconReply";
export { default as IconSearch } from "./IconSearch";
export { default as IconSet } from "./IconSet";
export { default as IconSetChat } from "./IconSetChat";
export { default as IconSetting } from "./IconSetting";
export { default as IconStar } from "./IconStar";
export { default as IconStorage } from "./IconStorage";
export { default as IconSubcribe } from "./IconSubcribe";
export { default as IconSuka } from "./IconSuka";
export { default as IconToken } from "./IconToken";
export { default as IconVideo } from "./IconVideo";
export { default as IconWallet } from "./IconWallet";
export { default as IconWhisper } from "./IconWhisper";
