// DO NOT EDIT. This file is automatically generated.

export interface CallParticipant {
  id: string;
  call_id: string;
  user_id: string;
  joined_at: string;
  left_at: string | null;
  is_muted: boolean;
  is_video_enabled: boolean;
  created_at: string;
  updated_at: string;
}

export interface CallSession {
  id: string;
  conversation_id: string;
  initiator_user_id: string;
  call_type: CallType;
  call_status: string;
  started_at: string;
  ended_at: string | null;
  duration_seconds: number | null;
  signaling_payload: number[] | null;
  created_at: string;
  updated_at: string;
}

export interface Contact {
  id: string;
  owner_user_id: string;
  contact_user_id: string;
  saved_name: string;
  allow_show_contacts: boolean;
  created_at: string;
  updated_at: string;
}

export interface Category {
  id: string;
  name: string;
  created_at: string;
  updated_at: string;
}

export interface Tag {
  id: string;
  name: string;
  created_at: string;
  updated_at: string;
}

export interface Conversation {
  id: string;
  conversation_type: string;
  category_id: string | null;
  name: string | null;
  profile_url: string | null;
  cover_url: string | null;
  description: string | null;
  bio: string | null;
  is_public: boolean;
  owner_user_id: string;
  created_at: string;
  updated_at: string;
  category?: Category | null;
  tags?: Tag[] | null;
}

export interface ConversationMember {
  id: string;
  conversation_id: string;
  user_id: string;
  role: string;
  last_read_message: string | null;
  created_at: string;
  updated_at: string;
}

export interface Message {
  id: string;
  conversation_id: string;
  sender_user_id: string;
  cipher_text: string | null;
  nonce: number[] | null;
  tag: number[] | null;
  encryption_algo: string;
  reply_to_message_id: string | null;
  blockchain_hash: string | null;
  blockchain_tx_id: string | null;
  blockchain_chain: string | null;
  message_status: MessageStatus;
  created_at: string;
  updated_at: string;
}

export interface Profile {
  user_id: string;
  public_name: string;
  show_public_name: boolean;
  avatar_url: string | null;
  avatar_mime: string | null;
  background_url: string | null;
  background_mime: string | null;
  badge_url: string | null;
  badge_hover_url: string | null;
  badge_hover_mime: string | null;
  bio: string | null;
  created_at: string;
  updated_at: string;
}

export interface ConversationWithLastMessage {
  last_message?: Message | null;
  other_user?: Profile | null;
  id: string;
  conversation_type: string;
  category_id: string | null;
  name: string | null;
  profile_url: string | null;
  cover_url: string | null;
  description: string | null;
  bio: string | null;
  is_public: boolean;
  owner_user_id: string;
  created_at: string;
  updated_at: string;
  category?: Category | null;
  tags?: Tag[] | null;
}

export interface Friendship {
  id: string;
  user_id: string;
  friend_id: string;
  status: FriendshipStatusType;
  created_at: string;
  updated_at: string;
}

export interface FriendRequest {
  id: string;
  requester_id: string;
  receiver_id: string;
  status: FriendRequestStatusType;
  created_at: string;
  updated_at: string;
}

export interface MessageAttachment {
  id: string;
  message_id: string;
  url: string;
  mime: string | null;
  category: string;
  created_at: string;
  updated_at: string;
}

export interface MessageReaction {
  id: string;
  message_id: string;
  user_id: string;
  kind: string;
  custom_code: string | null;
  created_at: string;
  updated_at: string;
}

export interface Notification {
  id: string;
  user_id: string;
  type: string;
  title?: string | null;
  body: string;
  data?: { [key: string]: any } | null;
  status: NotificationStatus;
  priority: NotificationPriority;
  is_silent: boolean;
  created_at: string;
  updated_at: string;
}

export interface NotificationChannel {
  id: string;
  notification_id: string;
  channel: string;
  status: DeliveryStatus;
  sent_at?: string | null;
}

export interface Plan {
  id: string;
  code: string;
  name: string;
  price: number;
  currency: string;
  is_active: boolean;
  created_at: string;
  updated_at: string;
}

export interface Story {
  id: string;
  user_id: string;
  caption: string | null;
  expires_at: string;
  created_at: string;
  updated_at: string;
}

export interface StoryMedia {
  id: string;
  story_id: string;
  url: string;
  mime: string | null;
  category: string;
  created_at: string;
  updated_at: string;
}

export interface UserRole {
  id: string;
  user_id: string;
  role: Role;
  assigned_at: string;
  created_at: string;
  updated_at: string;
}

export interface User {
  id: string;
  username: string;
  email: string | null;
  is_active: boolean;
  created_at: string;
  updated_at: string;
  profile?: Profile | null;
  roles?: UserRole[] | null;
}

export interface UserAuthIdentity {
  id: string;
  user_id: string;
  provider: Provider;
  provider_uid: string;
  password_hash: string | null;
  created_at: string;
  updated_at: string;
}

export interface UserSubscription {
  id: string;
  user_id: string;
  plan_id: string;
  status: string;
  auto_renew: boolean;
  started_at: string;
  expires_at: string | null;
  created_at: string;
  updated_at: string;
}

export interface Web3Nonce {
  WalletAddress: string;
  Nonce: string;
  ExpiresAt: string;
}

export interface ConversationTag {
  conversation_id: string;
  tag_id: string;
  created_at: string;
}

export type CallType = "audio" | "video";

export type MessageStatus = "queued" | "sent" | "delivered" | "read" | "failed";

export type FriendshipStatusType = "active" | "blocked" | "removed";

export type FriendRequestStatusType =
  | "pending"
  | "accepted"
  | "rejected"
  | "cancelled";

export type NotificationStatus = "unread" | "read" | "archived";

export type NotificationPriority = "low" | "normal" | "high";

export type DeliveryStatus = "pending" | "sent" | "failed";

export type Role = "user" | "admin" | "moderator" | "system";

export type Provider = "internal" | "google" | "web3";

export type ConversationType = "direct" | "group" | "channel";

export type ConversationRole =
  | "owner"
  | "admin"
  | "moderator"
  | "member"
  | "guest";
